### PR TITLE
feat: recall last export folder

### PR DESCRIPTION
**Pull request by luusluus**

### CODE REVIEW

**Comment by darrylthom** [comment]
Does this work for opening in folder? I think the other will just open the folder but not highlight it

Does this work at all? I think if it's

// do not use vscode.Uri.parse
const yourUri = vscode.Uri.file(yourPath);
vscode.commands.executeCommand("revealFileInOS", yourUri);

**Comment by luusluus** [comment]
This should've been in another PR

**Comment by luusluus** [comment]
Vscode api doesn't natively support this. So I did it by spawning a OS process from nodejs. Currently I have it working to open explorer from wsl and open the directory the file is in. The auto selection I'll need to try. I also need to test this somehow for mac users, Linux users and windows users

**Comment by darrylthom** [comment]
> Vscode api doesn't natively support this. So I did it by spawning a OS process from nodejs. Currently I have it working to open explorer from wsl and open the directory the file is in. The auto selection I'll need to try. I also need to test this somehow for mac users, Linux users and windows users

I figured it was something like that, either way if there is no method to do it, the folder is still useful. Apologies if I am commenting in the wrong place.

**Comment by luusluus** [comment]
It's ok I pushed it into the wrong place. Your feedback is valuable. Now i need to figure out how to select the item in explorer.

**Comment by darrylthom** [comment]
> Owner

This worked for me in the command prompt:

explorer.exe /select, "C:\EasyAntiCheat_EOS_Setup.exe"

**Comment by luusluus** [comment]
> This worked for me in the command prompt:
> 
> explorer.exe /select, "C:\EasyAntiCheat_EOS_Setup.exe"

This worked. I'll push it in a different PR.

**Pull request merged**
